// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Animal.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dotnet.Protobuf.Animal {

  /// <summary>Holder for reflection information generated from Animal.proto</summary>
  public static partial class AnimalReflection {

    #region Descriptor
    /// <summary>File descriptor for Animal.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AnimalReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxBbmltYWwucHJvdG8SBmFuaW1hbCJECgZBbmltYWwSEgoKYW5pbWFsTmFt",
            "ZRgBIAEoCRImCgphbmltYWxUeXBlGAIgASgOMhIuYW5pbWFsLkFuaW1hbFR5",
            "cGUqNQoKQW5pbWFsVHlwZRILCgdVTktOT1dOEAASBwoDRE9HEAESBwoDQ0FU",
            "EAISCAoEQklSRBADQhmqAhZEb3RuZXQuUHJvdG9idWYuQW5pbWFsYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Dotnet.Protobuf.Animal.AnimalType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dotnet.Protobuf.Animal.Animal), global::Dotnet.Protobuf.Animal.Animal.Parser, new[]{ "AnimalName", "AnimalType" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum AnimalType {
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("DOG")] Dog = 1,
    [pbr::OriginalName("CAT")] Cat = 2,
    [pbr::OriginalName("BIRD")] Bird = 3,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Animal : pb::IMessage<Animal>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Animal> _parser = new pb::MessageParser<Animal>(() => new Animal());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Animal> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dotnet.Protobuf.Animal.AnimalReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Animal() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Animal(Animal other) : this() {
      animalName_ = other.animalName_;
      animalType_ = other.animalType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Animal Clone() {
      return new Animal(this);
    }

    /// <summary>Field number for the "animalName" field.</summary>
    public const int AnimalNameFieldNumber = 1;
    private string animalName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AnimalName {
      get { return animalName_; }
      set {
        animalName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "animalType" field.</summary>
    public const int AnimalTypeFieldNumber = 2;
    private global::Dotnet.Protobuf.Animal.AnimalType animalType_ = global::Dotnet.Protobuf.Animal.AnimalType.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Dotnet.Protobuf.Animal.AnimalType AnimalType {
      get { return animalType_; }
      set {
        animalType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Animal);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Animal other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AnimalName != other.AnimalName) return false;
      if (AnimalType != other.AnimalType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AnimalName.Length != 0) hash ^= AnimalName.GetHashCode();
      if (AnimalType != global::Dotnet.Protobuf.Animal.AnimalType.Unknown) hash ^= AnimalType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AnimalName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AnimalName);
      }
      if (AnimalType != global::Dotnet.Protobuf.Animal.AnimalType.Unknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) AnimalType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AnimalName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AnimalName);
      }
      if (AnimalType != global::Dotnet.Protobuf.Animal.AnimalType.Unknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) AnimalType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AnimalName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AnimalName);
      }
      if (AnimalType != global::Dotnet.Protobuf.Animal.AnimalType.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AnimalType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Animal other) {
      if (other == null) {
        return;
      }
      if (other.AnimalName.Length != 0) {
        AnimalName = other.AnimalName;
      }
      if (other.AnimalType != global::Dotnet.Protobuf.Animal.AnimalType.Unknown) {
        AnimalType = other.AnimalType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            AnimalName = input.ReadString();
            break;
          }
          case 16: {
            AnimalType = (global::Dotnet.Protobuf.Animal.AnimalType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            AnimalName = input.ReadString();
            break;
          }
          case 16: {
            AnimalType = (global::Dotnet.Protobuf.Animal.AnimalType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
